### PR TITLE
Fix SCRIPT1003 error in IE11

### LINKED ISSUE #6: Breaks IE11 (which is supported by docsify v4)
This plugin is using [ES2015 method definition shorthand syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) which is not supported by IE11:

https://github.com/njleonzhang/docsify-plugin-codefund/blob/4438c6cbd6d334a0916876d7468999465b562553/index.js#L17-L28

Since IE11 is [officially support by docsify](http://localhost:8080/#/?id=features), docsify plugins should be authored using only ES5 or transpiled from ES6+ to ES5 using a tool like [Babel](https://babeljs.io/). This plugin is used on [docsify.js.org](https://docsify.js.org/) which fails to load properly in IE11 as a result of this issue.

Thanks!

### PR DESCRIPTION
**Pull request by kirbyfern**
This PR will fix #6 issue

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -14,14 +14,14 @@
       }
     },
 
-    injectCodeFundContainer() {
+    injectCodeFundContainer: function() {
```
Comment (kirbyfern) [inline index.js:17]: #7

**Review by kirbyfern — COMMENTED** [review]
Since method definitions are not valid in IE11, function names should be...

**Comment by njleonzhang** [comment]
tnx for contribution.
